#!/usr/bin/env bash
# Script that performs a 301 redirection

sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

string_to_redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/HillaArts permanent;"

sudo sed -i "s/server_name _;/$string_to_redirect/" /etc/nginx/sites-enabled/default

# Use the service command or nginx direct command to restart nginx
# Uncomment the method you prefer:

# Using service (common in older systems or systems without systemd):
# sudo service nginx restart

# Using nginx commands directly:
sudo nginx -s reload
