#!/usr/bin/env bash
#Configures Nginx to add a custom HTTP header X-Served-By with the hostname

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo service nginx start

# Fetch the hostname of the server
HOSTNAME=$(hostname)

# Configure Nginx to add the custom header
# Create a configuration file in sites-available if not exists and enable it
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}" | sudo tee /etc/nginx/sites-available/custom_header

# Enable the configuration by linking it to the sites-enabled directory
sudo ln -sf /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
