#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  frontend
        bind *:80
        mode http
        default_backend backend
backend backend
        balance roundrobin
        server 245394-web-01 54.157.133.197:80 check
        server 245394-web-02 54.87.237.85:80 check
"
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
