#!/usr/bin/env bash
# Install the load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 245394-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 245394-web-02 54.87.237.85:80 check\n\tserver 245394-web-01 54.157.133.197.142:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
